#!/bin/sh
set -e

case "$1" in
  remove|deconfigure)
    systemctl stop alderpointdns.service alderpointdns-analytics.service alderpointdns-backup.timer >/dev/null 2>&1 || true
    ;;
esac

#DEBHELPER#
exit 0
