"""V2 isolated dnsdist runtime-config generation prototype (Workstream 3,
§8, §10).

Generates a dnsdist Lua config from compiled V2 policy inputs and runs it
through the real `dnsdist --check-config` validator via
``app/v2/runtime_staging.py`` before it could ever be promoted anywhere.
This module never writes to `/etc/dnsdist` or the live
`alderpointdns.service`/`dnsdist.service` units — every path used by
callers in this workstream is a tempdir under ``dev/`` or `/tmp`.

Scope for tonight: listener/ACL/upstream-server generation from a compiled
network table + upstream profile list, validated end-to-end against the
real installed dnsdist binary. Client-identification/packet-cache-profile
wiring (§35) is a separate feasibility question — see
``docs/v2/dnsdist-packet-cache-feasibility.md`` — not implemented here
beyond an explanatory comment block per generated server pool, since a
correct implementation depends on dnsdist Lua policy hooks this workstream
did not have time to prototype end-to-end.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from app.v2.network_match import NetworkScope
from app.v2.runtime_staging import (
    PromotionResult,
    Validator,
    run_command_validator,
    stage_validate_promote,
)

_LABEL_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,64}$")


class DnsdistGenError(ValueError):
    pass


@dataclass(frozen=True)
class UpstreamServer:
    name: str
    address: str  # "ip:port"
    pool: str = ""

    def __post_init__(self) -> None:
        if not _LABEL_RE.match(self.name):
            raise DnsdistGenError(f"invalid upstream server name: {self.name!r}")
        if not _LABEL_RE.match(self.address):
            raise DnsdistGenError(f"invalid upstream address: {self.address!r}")


def _lua_string(s: str) -> str:
    # Only ever called on values already validated by _LABEL_RE above, but
    # escape defensively anyway rather than trust that invariant silently.
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate_dnsdist_config(
    listen_address: str,
    acl_networks: list[NetworkScope],
    upstreams: list[UpstreamServer],
    cache_profile_summary: dict[str, str] | None = None,
    refused_domains: list[str] | None = None,
) -> str:
    """Pure function: same inputs -> byte-identical config text. Only
    accepts already-validated ``NetworkScope``/``UpstreamServer`` value
    objects (their own constructors reject malformed CIDRs/labels), so this
    function does not re-validate untrusted strings itself — it composes
    trusted pieces.
    """
    if not _LABEL_RE.match(listen_address.split(":")[0]) and ":" not in listen_address:
        raise DnsdistGenError(f"invalid listen_address: {listen_address!r}")
    if not upstreams:
        raise DnsdistGenError("at least one upstream server is required")

    lines = [
        "-- Generated by app/v2/dnsdist_gen.py -- V2 PROTOTYPE, NOT the live config.",
        "-- Do not hand-edit; regenerate from the effective policy compiler.",
        f'setLocal("{listen_address}")',
        "",
    ]

    for scope in acl_networks:
        lines.append(f'addACL("{scope.cidr}")  -- network: {scope.network_id}')
    if acl_networks:
        lines.append("")

    pools: dict[str, list[UpstreamServer]] = {}
    for up in upstreams:
        pools.setdefault(up.pool, []).append(up)

    for pool_name, servers in pools.items():
        pool_comment = f" (pool: {pool_name})" if pool_name else " (default pool)"
        lines.append(f"-- upstream pool{pool_comment}")
        for srv in servers:
            pool_kw = f', {{pool={_lua_string(pool_name)}}}' if pool_name else ""
            lines.append(f'newServer({{address={_lua_string(srv.address)}{pool_kw}}})')
        lines.append("")

    refused_lines = render_refused_block_rules(refused_domains or [])
    if refused_lines:
        lines.extend(refused_lines)
        lines.append("")

    if cache_profile_summary:
        lines.append("-- Effective cache profile summary (diagnostic only, not enforced here):")
        lines.append(
            "-- Packet-cache partitioning by effective policy is NOT implemented in this"
        )
        lines.append(
            "-- prototype -- see docs/v2/dnsdist-packet-cache-feasibility.md. Distinct"
        )
        lines.append("-- profile ids observed at compile time:")
        for profile_id, note in sorted(cache_profile_summary.items()):
            lines.append(f"--   {profile_id}: {note}")
        lines.append("")

    return "\n".join(lines) + "\n"


# Maps app/v2/policy_store.py's upstream_profiles.strategy values to real
# dnsdist 2.1.1 server-selection policies (verified against the installed
# binary via --check-config, not assumed from documentation alone).
# "parallel_first_success" has no native stock dnsdist policy in this
# version -- true fan-out-and-take-first-response requires custom Lua this
# workstream did not have time to build and validate, so it's rejected
# rather than silently mapped to something that doesn't actually behave
# that way (§11 "do not invent semantics unsupported by target runtime").
_STRATEGY_TO_DNSDIST_POLICY = {
    "ordered": "firstAvailable",
    "failover": "firstAvailable",
    "load_balanced": "leastOutstanding",
}


def generate_dnsdist_config_from_profiles(
    listen_address: str,
    acl_networks: list[NetworkScope],
    default_profile,  # policy_store.UpstreamProfileRecord
    domain_routing: "list[tuple[str, object]] | None" = None,
    ecs_policy=None,  # app.v2.ecs_policy.EcsPolicy, optional
    refused_domains: list[str] | None = None,
) -> str:
    """Compiles real ``policy_store.UpstreamProfileRecord``s (§7-9) into a
    dnsdist config: the default profile's endpoints become the unnamed
    default pool with its strategy applied via ``setServerPolicy``;
    ``domain_routing`` is an optional list of ``(suffix_domain,
    UpstreamProfileRecord)`` pairs, each becoming a named pool plus a
    ``SuffixMatchNodeRule`` -> ``PoolAction`` routing rule (§9).

    Precedence (P0-C fix): the generator itself enforces most-specific-
    suffix-wins, deterministically, regardless of the order ``domain_routing``
    is passed in -- entries are sorted here by suffix length descending
    (longer/deeper suffix = more specific), tied-broken by the suffix
    string itself, *before* any Lua is emitted. ``PoolAction`` is a
    terminal dnsdist rule action (it stops further rule evaluation once
    matched), so emitting rules most-specific-first in file order is what
    makes "most specific wins" true at runtime, not just in this function's
    internal ordering. A duplicate suffix mapped to two different upstream
    profiles is an explicit conflict and raises rather than silently
    picking one arbitrarily.
    """
    if default_profile.strategy not in _STRATEGY_TO_DNSDIST_POLICY:
        raise DnsdistGenError(
            f"upstream strategy {default_profile.strategy!r} has no supported native "
            f"dnsdist policy in this generator (supported: "
            f"{sorted(_STRATEGY_TO_DNSDIST_POLICY)})"
        )

    lines = [
        "-- Generated by app/v2/dnsdist_gen.py -- V2 PROTOTYPE, NOT the live config.",
        "-- Do not hand-edit; regenerate from the effective policy compiler.",
        f'setLocal("{listen_address}")',
        "",
    ]
    for scope in acl_networks:
        lines.append(f'addACL("{scope.cidr}")  -- network: {scope.network_id}')
    if acl_networks:
        lines.append("")

    use_ecs = False
    if ecs_policy is not None:
        from app.v2.ecs_policy import render_dnsdist_directives, server_uses_client_subnet

        directives = render_dnsdist_directives(ecs_policy)
        if directives:
            lines.append(f"-- ECS policy: {ecs_policy.mode}")
            lines.extend(directives)
            lines.append("")
        use_ecs = server_uses_client_subnet(ecs_policy)

    def _server_line(address: str, pool: str | None) -> str:
        kwargs = f"address={_lua_string(address)}"
        if pool:
            kwargs += f", pool={_lua_string(pool)}"
        if use_ecs:
            kwargs += ", useClientSubnet=true"
        return f"newServer({{{kwargs}}})"

    lines.append(f"-- default upstream profile: {default_profile.upstream_profile_id}")
    for ep in default_profile.endpoints:
        lines.append(_server_line(ep.address, None))
    lines.append(f"setServerPolicy({_STRATEGY_TO_DNSDIST_POLICY[default_profile.strategy]})")
    lines.append("")

    normalized_routes: dict[str, object] = {}
    for suffix_domain, profile in domain_routing or []:
        key = suffix_domain.strip(".").lower()
        if key in normalized_routes and normalized_routes[key].upstream_profile_id != profile.upstream_profile_id:
            raise DnsdistGenError(
                f"conflicting domain routing rule for {key!r}: both "
                f"{normalized_routes[key].upstream_profile_id!r} and "
                f"{profile.upstream_profile_id!r} were specified"
            )
        normalized_routes[key] = profile

    # Most-specific-first, deterministic regardless of input order (P0-C).
    ordered_routes = sorted(normalized_routes.items(), key=lambda kv: (-len(kv[0]), kv[0]))

    for suffix_domain, profile in ordered_routes:
        if profile.strategy not in _STRATEGY_TO_DNSDIST_POLICY:
            raise DnsdistGenError(
                f"upstream strategy {profile.strategy!r} for domain route {suffix_domain!r} "
                f"has no supported native dnsdist policy"
            )
        pool_name = f"route_{profile.upstream_profile_id}"
        lines.append(f"-- domain routing pool for {suffix_domain}: {profile.upstream_profile_id}")
        for ep in profile.endpoints:
            lines.append(_server_line(ep.address, pool_name))
        trigger = suffix_domain + "."
        lines.append(
            f'addAction(SuffixMatchNodeRule({{{_lua_string(trigger)}}}), PoolAction({_lua_string(pool_name)}))'
        )
        lines.append("")

    refused_lines = render_refused_block_rules(refused_domains or [])
    if refused_lines:
        lines.extend(refused_lines)
        lines.append("")

    return "\n".join(lines) + "\n"


def render_refused_block_rules(domains: list[str]) -> tuple[str, ...]:
    """The authoritative implementation of ``blocking_response.py``'s
    ``refused`` mode (P0-B fix): a real dnsdist ``RCodeAction`` that
    actually returns RCODE REFUSED to the client, verified end-to-end
    against the installed dnsdist 2.1.1 binary (a live isolated instance
    queried for a REFUSED-mode domain returns RCODE 5; an unrelated domain
    returns RCODE 0) -- not the RPZ ``rpz-drop`` substitute, which merely
    drops the query (client sees a timeout, not RCODE REFUSED). All
    REFUSED-mode domains are batched into one ``SuffixMatchNodeRule`` rule
    rather than one rule per domain, since dnsdist evaluates its rule chain
    linearly per query and a long chain of single-domain rules would add
    unnecessary per-query overhead on the hot path.
    """
    if not domains:
        return ()
    normalized = sorted(set(d.strip(".").lower() + "." for d in domains if d.strip(".")))
    if not normalized:
        return ()
    domain_list = ", ".join(_lua_string(d) for d in normalized)
    return (
        "-- REFUSED blocking-response-mode domains (real RCODE, not rpz-drop)",
        f"addAction(SuffixMatchNodeRule({{{domain_list}}}), RCodeAction(DNSRCode.REFUSED))",
    )


def dnsdist_check_config_validator(binary: str = "dnsdist") -> Validator:
    # dnsdist's --check-config silently validates the DEFAULT config path
    # (/etc/dnsdist/dnsdist.conf) if given a bare positional argument
    # instead of -C/--config -- a real footgun found while wiring this up
    # (a malformed staged file was reported "Configuration OK" because the
    # live system config was checked instead). -C must be explicit.
    return run_command_validator([binary, "-C", "{path}", "--check-config"])


def stage_and_validate_dnsdist_config(
    staging_root: Path,
    config_text: str,
    live_path: Path,
    binary: str = "dnsdist",
) -> PromotionResult:
    """Stages+validates+promotes into an isolated ``live_path`` (a test
    fixture path, never the real `/etc/dnsdist/dnsdist.conf`). No health
    check is wired here yet — that requires an actually-running isolated
    dnsdist instance, which is beyond tonight's validation-only proof.
    """
    return stage_validate_promote(
        staging_root=staging_root,
        name="dnsdist.conf",
        content=config_text,
        live_path=live_path,
        validator=dnsdist_check_config_validator(binary),
    )
