"""V2 isolated dnsdist runtime-config generation prototype (Workstream 3,
§8, §10).

Generates a dnsdist Lua config from compiled V2 policy inputs and runs it
through the real `dnsdist --check-config` validator via
``app/v2/runtime_staging.py`` before it could ever be promoted anywhere.
This module never writes to `/etc/dnsdist` or the live
`alderpointdns.service`/`dnsdist.service` units — every path used by
callers in this workstream is a tempdir under ``dev/`` or `/tmp`.

Scope for tonight: listener/ACL/upstream-server generation from a compiled
network table + upstream profile list, validated end-to-end against the
real installed dnsdist binary. Client-identification/packet-cache-profile
wiring (§35) is a separate feasibility question — see
``docs/v2/dnsdist-packet-cache-feasibility.md`` — not implemented here
beyond an explanatory comment block per generated server pool, since a
correct implementation depends on dnsdist Lua policy hooks this workstream
did not have time to prototype end-to-end.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from app.v2.network_match import NetworkScope
from app.v2.runtime_staging import (
    PromotionResult,
    Validator,
    run_command_validator,
    stage_validate_promote,
)

_LABEL_RE = re.compile(r"^[A-Za-z0-9_.:-]{1,64}$")


class DnsdistGenError(ValueError):
    pass


@dataclass(frozen=True)
class UpstreamServer:
    name: str
    address: str  # "ip:port"
    pool: str = ""

    def __post_init__(self) -> None:
        if not _LABEL_RE.match(self.name):
            raise DnsdistGenError(f"invalid upstream server name: {self.name!r}")
        if not _LABEL_RE.match(self.address):
            raise DnsdistGenError(f"invalid upstream address: {self.address!r}")


def _lua_string(s: str) -> str:
    # Only ever called on values already validated by _LABEL_RE above, but
    # escape defensively anyway rather than trust that invariant silently.
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate_dnsdist_config(
    listen_address: str,
    acl_networks: list[NetworkScope],
    upstreams: list[UpstreamServer],
    cache_profile_summary: dict[str, str] | None = None,
) -> str:
    """Pure function: same inputs -> byte-identical config text. Only
    accepts already-validated ``NetworkScope``/``UpstreamServer`` value
    objects (their own constructors reject malformed CIDRs/labels), so this
    function does not re-validate untrusted strings itself — it composes
    trusted pieces.
    """
    if not _LABEL_RE.match(listen_address.split(":")[0]) and ":" not in listen_address:
        raise DnsdistGenError(f"invalid listen_address: {listen_address!r}")
    if not upstreams:
        raise DnsdistGenError("at least one upstream server is required")

    lines = [
        "-- Generated by app/v2/dnsdist_gen.py -- V2 PROTOTYPE, NOT the live config.",
        "-- Do not hand-edit; regenerate from the effective policy compiler.",
        f'setLocal("{listen_address}")',
        "",
    ]

    for scope in acl_networks:
        lines.append(f'addACL("{scope.cidr}")  -- network: {scope.network_id}')
    if acl_networks:
        lines.append("")

    pools: dict[str, list[UpstreamServer]] = {}
    for up in upstreams:
        pools.setdefault(up.pool, []).append(up)

    for pool_name, servers in pools.items():
        pool_comment = f" (pool: {pool_name})" if pool_name else " (default pool)"
        lines.append(f"-- upstream pool{pool_comment}")
        for srv in servers:
            pool_kw = f', {{pool={_lua_string(pool_name)}}}' if pool_name else ""
            lines.append(f'newServer({{address={_lua_string(srv.address)}{pool_kw}}})')
        lines.append("")

    if cache_profile_summary:
        lines.append("-- Effective cache profile summary (diagnostic only, not enforced here):")
        lines.append(
            "-- Packet-cache partitioning by effective policy is NOT implemented in this"
        )
        lines.append(
            "-- prototype -- see docs/v2/dnsdist-packet-cache-feasibility.md. Distinct"
        )
        lines.append("-- profile ids observed at compile time:")
        for profile_id, note in sorted(cache_profile_summary.items()):
            lines.append(f"--   {profile_id}: {note}")
        lines.append("")

    return "\n".join(lines) + "\n"


def dnsdist_check_config_validator(binary: str = "dnsdist") -> Validator:
    # dnsdist's --check-config silently validates the DEFAULT config path
    # (/etc/dnsdist/dnsdist.conf) if given a bare positional argument
    # instead of -C/--config -- a real footgun found while wiring this up
    # (a malformed staged file was reported "Configuration OK" because the
    # live system config was checked instead). -C must be explicit.
    return run_command_validator([binary, "-C", "{path}", "--check-config"])


def stage_and_validate_dnsdist_config(
    staging_root: Path,
    config_text: str,
    live_path: Path,
    binary: str = "dnsdist",
) -> PromotionResult:
    """Stages+validates+promotes into an isolated ``live_path`` (a test
    fixture path, never the real `/etc/dnsdist/dnsdist.conf`). No health
    check is wired here yet — that requires an actually-running isolated
    dnsdist instance, which is beyond tonight's validation-only proof.
    """
    return stage_validate_promote(
        staging_root=staging_root,
        name="dnsdist.conf",
        content=config_text,
        live_path=live_path,
        validator=dnsdist_check_config_validator(binary),
    )
