"""V2 local DoH-egress transport (Gate #3 acceptance closure §4).

BIND has no native DoH-forwarder capability at all -- not a
configuration gap, an actual missing feature (confirmed: no upstream
DoH support in any BIND 9.20 ``forwarders``/``tls`` clause). To preserve
the locked BIND recursive-cache tier for DoH upstream selections without
sending the client-facing dnsdist path directly to the DoH upstream
(bypassing BIND's cache entirely), this module generates a minimal,
bounded, package-managed (dnsdist is already a base Depends -- no new
runtime, no Python/FastAPI) local egress instance: a second, dedicated
dnsdist process listening on loopback only, whose only job is
plain-DNS-in -> DoH-out, using dnsdist's own already-proven-live DoH
backend syntax (the exact pattern verified in
``app/v2/dnsdist_gen.py``'s own DoH backend generation, Gate #2
Blocker 1 fix).

Chain: client -> dnsdist (client-facing, policy/routing/cache) -> BIND
context (recursive cache) -> this local egress dnsdist -> DoH upstream.

Isolation: entirely separate loopback ports from both the client-facing
dnsdist instance and every BIND context (see ``DOH_EGRESS_PORT_BASE``),
one process per distinct DoH upstream selection (same port-based,
one-process-per-selection pattern already proven for
``app/v2/bind_gen.py``'s multi-context BIND design, for the same reason:
no extra loopback-IP/CAP_NET_ADMIN infrastructure needed).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from app.v2.dnsdist_gen import (
    DnsdistGenError,
    _LABEL_RE,
    _lua_string,
    dnsdist_check_config_validator,
)
from app.v2.runtime_staging import PromotionResult, Validator, stage_validate_promote

# Disjoint from the client-facing dnsdist listener, from every V2 BIND
# context's own ports (5453+/5553+), and from V1's own ports.
DOH_EGRESS_PORT_BASE = 5653
MAX_DOH_EGRESS_CONTEXTS = 4


@dataclass(frozen=True)
class DohEgressContext:
    name: str
    upstream_address: str  # "ip:port", e.g. "1.1.1.1:443"
    doh_path: str
    tls_hostname: str
    listen_port: int

    def __post_init__(self) -> None:
        if not _LABEL_RE.match(self.upstream_address):
            raise DnsdistGenError(f"invalid DoH upstream address: {self.upstream_address!r}")
        if not self.tls_hostname:
            raise DnsdistGenError("DoH egress context requires a tls_hostname to verify the peer certificate")


def allocate_doh_egress_contexts(
    selections: list[tuple[str, str, str]],  # (upstream_address, doh_path, tls_hostname)
) -> list[DohEgressContext]:
    """Same deterministic, bounded allocation pattern as
    ``app/v2/bind_gen.allocate_bind_contexts`` -- only the first
    ``MAX_DOH_EGRESS_CONTEXTS`` distinct selections get a real egress
    process; callers must keep any excess routed direct-to-upstream from
    dnsdist (bypassing BIND for that selection only), same documented,
    conservative bound as the BIND side.
    """
    contexts = []
    for i, (addr, path, hostname) in enumerate(selections[:MAX_DOH_EGRESS_CONTEXTS]):
        contexts.append(
            DohEgressContext(
                name=f"dohctx{i}", upstream_address=addr, doh_path=path, tls_hostname=hostname,
                listen_port=DOH_EGRESS_PORT_BASE + i,
            )
        )
    return contexts


def egress_backend_address(ctx: DohEgressContext) -> str:
    """The address a BIND context's forwarders should point at for this
    DoH selection -- plain DNS to the local egress process, which then
    re-encrypts to the real DoH upstream."""
    return f"127.0.0.1:{ctx.listen_port}"


def render_egress_config(ctx: DohEgressContext) -> str:
    """Pure function: the local egress dnsdist's own Lua config. Real,
    verified-live DoH backend syntax (identical pattern already proven
    in app/v2/dnsdist_gen.py's own DoH generation): ``tls="openssl"``,
    ``dohPath=<path>``, ``subjectName=<hostname>`` -- dnsdist verifies
    the upstream's certificate against this hostname, same guarantee the
    client-facing path already provides for direct DoH dispatch.
    """
    kwargs = (
        f'address={_lua_string(ctx.upstream_address)}, tls="openssl", '
        f'dohPath={_lua_string(ctx.doh_path)}, subjectName={_lua_string(ctx.tls_hostname)}'
    )
    return "\n".join([
        "-- Generated by app/v2/doh_egress_gen.py -- local DoH-egress transport",
        "-- (Gate #3 acceptance closure #4). Do not hand-edit; regenerate from",
        "-- the effective policy compiler.",
        f'setLocal("127.0.0.1:{ctx.listen_port}")',
        "",
        f"newServer({{{kwargs}}})",
        "",
    ]) + "\n"


def stage_and_validate_egress_config(
    staging_root: Path, ctx: DohEgressContext, live_path: Path, binary: str = "dnsdist",
) -> PromotionResult:
    return stage_validate_promote(
        staging_root=staging_root,
        name=f"{ctx.name}/dnsdist.conf",
        content=render_egress_config(ctx),
        live_path=live_path,
        validator=dnsdist_check_config_validator(binary),
    )
