<script lang="ts">
  import { onMount } from "svelte";
  import { api, ApiError, type DnsTransportSettings, type TlsStatus, type DNSRuntimeApplyResult } from "../api";
  import { router } from "../router.svelte";
  import { timestampPref } from "../timestamp.svelte";
  import DnsRuntimeBadge from "./DnsRuntimeBadge.svelte";
  import ConfirmDialog from "./ui/ConfirmDialog.svelte";

  // Encryption. Two independently-scoped native pieces:
  //
  //  - TLS Certificate: this control plane's OWN real management
  //    certificate (the same one its HTTPS listener serves, and DoT/DoH
  //    reuse -- matching Python's own "single appliance-wide cert"
  //    design). Real upload/replace (internal/tlscert's write side,
  //    field-matched against Python's own app/v2/tls_cert.py): a bad
  //    replacement is validated BEFORE anything on disk changes and
  //    never touches the currently-working certificate. Matches
  //    Python's own real, disclosed behavior: promoting a new
  //    certificate needs a restart to actually take effect (a
  //    process-level TLS listener does not hot-reload), not a defect.
  //  - DNS Transport settings (DoT/DoH/DoQ/DoH3/DNSCrypt enable+port).
  //    All five compile into and auto-apply to the real DNS runtime.
  //    DNSCrypt additionally needs a real provider identity + signed
  //    resolver certificate before it can be enabled -- generated by
  //    the real installed dnsdist binary itself (internal/
  //    dnscryptprovision), never hand-rolled crypto -- via the
  //    Provision/Rotate actions below.

  let settings = $state<DnsTransportSettings | null>(null);
  let loadError = $state("");
  let saveError = $state("");
  let saveResult = $state("");
  let saving = $state(false);
  let dnsRuntimeResult = $state<DNSRuntimeApplyResult | null>(null);

  let tls = $state<TlsStatus | null>(null);
  let certFile: FileList | undefined = $state();
  let keyFile: FileList | undefined = $state();
  let replaceBusy = $state(false);
  let replaceError = $state("");
  let replaceResult = $state("");

  async function loadAll() {
    loadError = "";
    try {
      const [t, s] = await Promise.all([api.getDnsTransports(router.signal()), api.tlsStatus(router.signal())]);
      settings = t;
      tls = s;
    } catch (err) {
      if (err instanceof DOMException && err.name === "AbortError") return;
      loadError = err instanceof ApiError ? err.message : String(err);
    }
  }

  onMount(() => {
    loadAll();
  });

  async function replaceCert(e: Event) {
    e.preventDefault();
    const cf = certFile?.[0];
    const kf = keyFile?.[0];
    if (!cf || !kf) return;
    replaceBusy = true;
    replaceError = "";
    replaceResult = "";
    try {
      const [certificatePem, privateKeyPem] = await Promise.all([cf.text(), kf.text()]);
      const result = await api.tlsReplace(certificatePem, privateKeyPem);
      replaceResult = `Promoted: ${result.subject}. A restart is required for this control plane to actually serve it.`;
      await loadAll();
    } catch (err) {
      replaceError = err instanceof ApiError ? err.message : String(err);
    } finally {
      replaceBusy = false;
    }
  }

  async function save() {
    if (!settings) return;
    saving = true;
    saveError = "";
    saveResult = "";
    try {
      settings = await api.updateDnsTransports(settings);
      dnsRuntimeResult = settings.dns_runtime ?? null;
      saveResult = "Saved.";
    } catch (err) {
      saveError = err instanceof ApiError ? err.message : String(err);
    } finally {
      saving = false;
    }
  }

  // --- Client-facing address resolution -----------------------------
  //
  // The real, disclosed defects this replaces, in order:
  //
  //   1. (2026-09-02) Every manual-setup card interpolated
  //      settings.server_hostname directly -- simply the active TLS
  //      cert's first SAN entry, which on a fresh appliance is
  //      "localhost". Fixed by deriving a client-facing address instead.
  //   2. (2026-09-03, owner report) That fix's own fallback --
  //      settings.lan_ip -- was detected via net.InterfaceAddrs() INSIDE
  //      THE WEB CONTAINER's own isolated Podman network namespace,
  //      which showed 10.88.0.15 (a container bridge address) as if a
  //      phone or router could reach it. No LAN device ever can.
  //
  // The real fix: apdns-hostagent (the only process that ever sees the
  // HOST's own real network namespace) now reports real LAN candidates,
  // and the backend computes an authoritative effective_client_address
  // using, in order: an explicit owner preference/saved value, a real
  // (non-loopback) cert hostname, any owner-saved fallback, or EXACTLY
  // ONE detected host LAN candidate -- never guessing when detection is
  // ambiguous (zero or more than one). This page trusts that backend
  // value rather than re-deriving its own from settings.lan_ip, and
  // surfaces "choose a client-facing address" whenever the backend says
  // client_facing_selection_required.
  function isLoopbackName(h: string): boolean {
    return h === "localhost" || h === "127.0.0.1" || h === "::1";
  }
  function isIpAddress(s: string): boolean {
    return /^\d{1,3}(\.\d{1,3}){3}$/.test(s) || s.includes(":");
  }

  const certSan = $derived(settings?.cert_san ?? []);
  const lanIp = $derived(settings?.lan_ip ?? "");
  const lanIps = $derived(settings?.lan_ips ?? []);
  const lanDetectionAmbiguous = $derived(settings?.lan_detection_ambiguous ?? true);
  const hostagentReachable = $derived(settings?.hostagent_reachable ?? false);
  const rawCertHostname = $derived(settings?.server_hostname ?? "");
  const certHostnameIsLoopback = $derived(isLoopbackName(rawCertHostname));

  /** The backend's own authoritative "what should a client actually be told" value.
   *  Never derived independently client-side -- the backend also gates mobileconfig
   *  generation on this exact same computation, so this page must never disagree with it. */
  const clientAddress = $derived(settings?.effective_client_address ?? "");
  const clientAddressIsLanFallback = $derived(!!clientAddress && clientAddress === lanIp && (!rawCertHostname || certHostnameIsLoopback));
  const noClientAddress = $derived(!settings || (settings.client_facing_selection_required ?? clientAddress === ""));
  const clientAddressIsIp = $derived(isIpAddress(clientAddress));
  /** Would a client validating the TLS cert against clientAddress succeed? DNSCrypt doesn't use
   *  the TLS cert at all (its own provider key is the trust anchor), so this only gates
   *  DoT/DoH/DoQ/DoH3 -- see each fieldset below. */
  const clientAddressCertValid = $derived(!!clientAddress && certSan.includes(clientAddress));
  /** Android's Private DNS "hostname" field rejects raw IP addresses on stock Android -- it needs
   *  a real, cert-covered DNS name. */
  const androidPrivateDnsUsable = $derived(clientAddressCertValid && !clientAddressIsIp);

  let rotateBusy = $state(false);
  let rotateResult = $state("");
  let rotateError = $state("");
  let confirmRotateProvider = $state(false);

  async function rotateDnscrypt(rotateProvider: boolean) {
    if (rotateProvider) {
      confirmRotateProvider = true;
      return;
    }
    await doRotateDnscrypt(false);
  }

  async function doRotateDnscrypt(rotateProvider: boolean) {
    rotateBusy = true;
    rotateError = "";
    rotateResult = "";
    try {
      const result = await api.rotateDnscrypt(rotateProvider);
      rotateResult = result.rotated_provider
        ? `New provider identity generated: ${result.fingerprint}`
        : `Certificate renewed (serial ${result.cert_serial}), same provider identity.`;
      await loadAll();
    } catch (err) {
      rotateError = err instanceof ApiError ? err.message : String(err);
    } finally {
      rotateBusy = false;
    }
  }
</script>

<section aria-labelledby="encryption-heading" class="encryption">
  <h2 id="encryption-heading">Encryption</h2>
  <p class="scope-note">
    The TLS Certificate is this appliance's own replaceable management certificate (also
    reused by DoT/DoH/DoQ/DoH3). DNS Transport settings apply automatically to the live DNS
    service as soon as they're saved. DNSCrypt needs a provider identity provisioned once before
    it can be enabled. Each enabled transport below shows the exact address to hand a client
    device, plus setup steps for the platforms that support it.
  </p>

  {#if settings && noClientAddress}
    <p class="degraded-note" role="alert">
      No client-facing address is available yet.
      {#if lanDetectionAmbiguous && hostagentReachable && lanIps.length > 1}
        This appliance has {lanIps.length} real LAN addresses ({lanIps.join(", ")}) and this
        control plane will not guess which one clients should use.
      {:else if !hostagentReachable}
        The host-control agent (the only thing that can see this box's real network -- never this
        web process's own isolated container network) is not reachable right now, so no LAN
        address could be detected.
      {:else}
        This appliance's TLS certificate has no real hostname (only "{rawCertHostname || "none"}")
        and no LAN address could be detected on this box.
      {/if}
      Choose a client-facing hostname and/or IP below before handing setup instructions to any
      client device -- nothing further down this page is safe to hand out yet.
    </p>
  {:else if settings && !clientAddressCertValid}
    <p class="degraded-note" role="status">
      This appliance's TLS certificate does not cover "{clientAddress}" -- its Subject Alternative
      Names are: {certSan.join(", ") || "none"}. Clients connecting to DoT/DoH/DoQ/DoH3 at this
      address will get a certificate validation error, so Apple profile downloads and Android
      Private DNS setup below are blocked until this is fixed. Replace the certificate with one
      whose SAN includes "{clientAddress}" (or point clients at a name/address the certificate
      does cover) -- DNSCrypt is unaffected, since it doesn't use this certificate at all.
    </p>
  {/if}

  {#if loadError}<p class="error" role="alert">{loadError}</p>{/if}

  <div class="card">
    <h3>TLS Certificate</h3>
    {#if !tls}
      <p class="hint">Loading…</p>
    {:else if !tls.active}
      <p class="degraded-note" role="status">
        {tls.error ? `Unavailable: ${tls.error}` : "No certificate available (not configured, or none provisioned yet)."}
      </p>
    {:else}
      <dl class="cert-info">
        <dt>Subject</dt>
        <dd>{tls.subject}</dd>
        <dt>Valid</dt>
        <dd>
          {tls.not_valid_before ? timestampPref.format(tls.not_valid_before) : "?"} &ndash;
          {tls.not_valid_after ? timestampPref.format(tls.not_valid_after) : "?"}
        </dd>
        <dt>Subject Alternative Names</dt>
        <dd>{(tls.san ?? []).join(", ") || "none"}</dd>
        <dt>Self-signed</dt>
        <dd>{tls.is_self_signed ? "Yes" : "No"}</dd>
      </dl>
    {/if}

    <form onsubmit={replaceCert} class="replace-form">
      <h4>Replace certificate</h4>
      <label>Certificate (PEM) <input type="file" bind:files={certFile} accept=".crt,.pem" aria-label="Certificate file" required /></label>
      <label>Private key (PEM) <input type="file" bind:files={keyFile} accept=".key,.pem" aria-label="Private key file" required /></label>
      <button type="submit" disabled={replaceBusy || !certFile?.[0] || !keyFile?.[0]}>{replaceBusy ? "Uploading…" : "Upload & Replace"}</button>
      {#if replaceResult}<p class="success" role="status">{replaceResult}</p>{/if}
      {#if replaceError}<p class="error" role="alert">{replaceError}</p>{/if}
    </form>
  </div>

  {#if settings}
    <div class="card">
      <h3>Client-Facing Address</h3>
      <p class="scope-note">
        What every setup card below tells a client device to connect to. Left blank, this control
        plane uses a real cert hostname when one exists, otherwise the one real LAN address
        detected on this box's actual host network (never a container-internal address) -- but
        will never guess if more than one real LAN address exists. Save an explicit hostname
        and/or IP here to override that, or to resolve an ambiguous detection.
      </p>
      <dl class="cert-info">
        <dt>Detected host LAN address(es)</dt>
        <dd>
          {#if !hostagentReachable}
            unavailable (host-control agent not reachable)
          {:else if lanIps.length === 0}
            none detected
          {:else}
            {lanIps.join(", ")}
          {/if}
        </dd>
        <dt>Currently in effect</dt>
        <dd>{clientAddress || "none -- choose one below"}</dd>
      </dl>
      <label>
        Client-facing hostname
        <input bind:value={settings.client_facing_hostname} placeholder="e.g. dns.example.com" />
      </label>
      <label>
        Client-facing IP
        <input bind:value={settings.client_facing_ip} placeholder="e.g. 172.16.43.100" />
      </label>
      <label>
        When both a hostname and an IP are set, prefer
        <select bind:value={settings.client_facing_prefer}>
          <option value="auto">Auto (real cert hostname, else IP)</option>
          <option value="hostname">Hostname</option>
          <option value="ip">IP</option>
        </select>
      </label>
      <p class="hint">
        Saved here with the rest of DNS Transports below -- click Save to apply. A localhost/
        loopback value or a Podman/Docker default bridge address (10.88.0.0/16, 10.89.0.0/16,
        172.17-172.31.x.x) is rejected outright; it is never a real client-facing address.
      </p>
    </div>

    <form class="card transports" onsubmit={(e) => { e.preventDefault(); save(); }}>
      <h3>DNS Transports</h3>

      <fieldset>
        <legend><label><input type="checkbox" bind:checked={settings.dot_enabled} /> DNS-over-TLS (DoT)</label></legend>
        <p class="transport-desc">
          Encrypts DNS lookups over a dedicated TLS connection (port 853 by default). Supported
          natively by most modern operating systems and routers.
        </p>
        <label class="port">Port <input type="number" min="1" max="65535" bind:value={settings.dot_port} /></label>
        {#if settings.dot_enabled}
          {@const addr = clientAddress || "(no client-facing address configured -- see warning above)"}
          <div class="manual-setup">
            <p class="manual-setup-label">Hostname / address clients should use:</p>
            <code>{addr}</code>, port <code>{settings.dot_port}</code> (some clients want the full URI: <code>tls://{addr}:{settings.dot_port}</code>)
            {#if clientAddressIsLanFallback && clientAddress}
              <p class="hint">This is this box's detected LAN IP (its certificate has no real hostname of its own yet) -- see the warning above.</p>
            {/if}
            {#if certHostnameIsLoopback}
              <p class="hint local-only">
                Only for commands run ON this appliance itself (e.g. <code>kdig -d @localhost -p {settings.dot_port} +tls example.com</code>) -- never hand "{rawCertHostname}" to another device.
              </p>
            {/if}

            <p class="manual-setup-label">Android (Settings &rarr; Network &amp; internet &rarr; Private DNS &rarr; Private DNS provider hostname):</p>
            {#if androidPrivateDnsUsable}
              <code>{addr}</code>
              <p class="hint">Enter exactly this hostname -- no <code>tls://</code> prefix, no port, and never an IP address.</p>
            {:else if !clientAddress}
              <p class="hint blocked">Blocked: no client-facing address is configured yet.</p>
            {:else if clientAddressIsIp}
              <p class="hint blocked">Blocked: Android's Private DNS field needs a real DNS hostname, not an IP address ("{addr}") -- configure a DNS name for this appliance and put it on the certificate to use Android Private DNS.</p>
            {:else}
              <p class="hint blocked">Blocked: the certificate doesn't cover "{addr}" yet -- Android will fail to validate it. Fix the certificate (see warning above) first.</p>
            {/if}

            <p class="manual-setup-label">Router / dnsmasq / stubby / unbound (forward to this resolver over DoT):</p>
            <code>tls_upstream_send_client_subnet: 0<br />tls_upstream: {addr}@{settings.dot_port}</code>
            <p class="hint">(stubby-style syntax shown; unbound uses <code>forward-tls-upstream: yes</code> plus a matching <code>forward-addr</code>/<code>forward-host</code> pair -- consult your router's own DoT forwarding docs for its exact syntax.)</p>

            <p class="manual-setup-label">Windows:</p>
            <p class="hint">Windows has no built-in DoT client; use a third-party stub resolver (e.g. YogaDNS) pointed at the hostname/port above, or configure DoT at the router instead.</p>
          </div>
          {#if clientAddressCertValid}
            <a class="mobileconfig-link" href="/api/dns-transports/mobileconfig/dot">
              Download an Apple .mobileconfig profile -- installs this DoT server as the device's
              resolver automatically. iOS/iPadOS/macOS only: <code>.mobileconfig</code> is Apple's
              own configuration-profile format, so every other platform uses the manual setup above
              instead.
            </a>
          {:else}
            <p class="hint blocked">Apple .mobileconfig download blocked: the certificate doesn't validate for "{addr}" yet (see warning above) -- Apple's profile installer would reject the connection.</p>
          {/if}
        {/if}
      </fieldset>

      <fieldset>
        <legend><label><input type="checkbox" bind:checked={settings.doh_enabled} /> DNS-over-HTTPS (DoH)</label></legend>
        <p class="transport-desc">
          Encrypts DNS lookups inside an HTTPS request. Supported by most modern browsers and
          operating systems, and the most broadly compatible encrypted option for clients that
          don't support DoT.
        </p>
        <label class="port">Port <input type="number" min="1" max="65535" bind:value={settings.doh_port} /></label>
        <label class="path">Path <input bind:value={settings.doh_path} placeholder="/dns-query" /></label>
        {#if settings.doh_enabled}
          {@const addr = clientAddress || "(no client-facing address configured -- see warning above)"}
          {@const portSuffix = settings.doh_port === 443 ? "" : `:${settings.doh_port}`}
          {@const dohUrl = `https://${addr}${portSuffix}${settings.doh_path}`}
          <div class="manual-setup">
            <p class="manual-setup-label">DoH server URL (this is what every client below wants):</p>
            <code>{dohUrl}</code>
            {#if clientAddress && !clientAddressCertValid}
              <p class="hint blocked">This won't validate yet -- the certificate doesn't cover "{addr}" (see warning above); browsers/apps will reject it as untrusted.</p>
            {/if}
            <p class="manual-setup-label">Firefox (Settings &rarr; Privacy &amp; Security &rarr; DNS over HTTPS &rarr; Custom):</p>
            <code>{dohUrl}</code>
            <p class="manual-setup-label">Chrome / Edge (Settings &rarr; Privacy and security &rarr; Security &rarr; Use secure DNS &rarr; With Custom):</p>
            <code>{dohUrl}</code>
            <p class="manual-setup-label">Windows 11 (Settings &rarr; Network &amp; internet &rarr; your connection &rarr; DNS server assignment &rarr; Edit &rarr; DNS over HTTPS on):</p>
            <p class="hint">
              Windows requires the plain IP address as the DNS server first, then lets you pick
              "On (encrypted only)" and enter this same DoH template URL for it. Windows 10 has no
              built-in DoH UI.
            </p>
            <p class="manual-setup-label">Android (Settings &rarr; Network &amp; internet &rarr; Private DNS):</p>
            <p class="hint">Android's Private DNS field only accepts a DoT hostname, not a DoH URL -- use the DoT transport above for Android instead.</p>
            <p class="manual-setup-label">Router / dnsmasq:</p>
            <p class="hint">
              dnsmasq has no native DoH client; most routers instead run a small local bridge
              (e.g. cloudflared or dnsproxy) that speaks DoH upstream and plain DNS to the LAN --
              point that bridge's upstream at the URL above.
            </p>
          </div>
          {#if clientAddressCertValid}
            <a class="mobileconfig-link" href="/api/dns-transports/mobileconfig/doh">
              Download an Apple .mobileconfig profile -- installs this DoH server as the device's
              resolver automatically. iOS/iPadOS/macOS only: <code>.mobileconfig</code> is Apple's
              own configuration-profile format, so every other platform uses the manual setup above
              instead.
            </a>
          {:else}
            <p class="hint blocked">Apple .mobileconfig download blocked: the certificate doesn't validate for "{addr}" yet (see warning above).</p>
          {/if}
        {/if}
      </fieldset>

      <fieldset>
        <legend><label><input type="checkbox" bind:checked={settings.doq_enabled} /> DNS-over-QUIC (DoQ)</label></legend>
        <p class="transport-desc">
          Encrypts DNS lookups over QUIC (UDP). Faster reconnection than DoT on unreliable
          networks; supported by a smaller set of clients (no Apple configuration profile format
          exists for DoQ yet).
        </p>
        <label class="port">Port <input type="number" min="1" max="65535" bind:value={settings.doq_port} /></label>
        {#if settings.doq_enabled}
          {@const addr = clientAddress || "(no client-facing address configured -- see warning above)"}
          <div class="manual-setup">
            <p class="manual-setup-label">Manual setup (a DoQ-capable client, e.g. dnscrypt-proxy or AdGuard's own apps):</p>
            <code>quic://{addr}:{settings.doq_port}</code>
            {#if clientAddress && !clientAddressCertValid}
              <p class="hint blocked">This won't validate yet -- the certificate doesn't cover "{addr}" (see warning above).</p>
            {/if}
            <p class="hint">
              No mainstream OS (Windows, Android, iOS/macOS) has a built-in DoQ setting, and there is
              no Apple configuration-profile format for DoQ -- it needs a client application that
              specifically supports DoQ.
            </p>
          </div>
        {/if}
      </fieldset>

      <fieldset>
        <legend><label><input type="checkbox" bind:checked={settings.doh3_enabled} /> DNS-over-HTTP/3 (DoH3)</label></legend>
        <p class="transport-desc">
          DNS-over-HTTPS carried over HTTP/3 (QUIC) instead of HTTP/2 -- same DoH semantics, faster
          on lossy networks, supported by a smaller set of clients.
        </p>
        <label class="port">Port <input type="number" min="1" max="65535" bind:value={settings.doh3_port} /></label>
        {#if settings.doh3_enabled}
          {@const addr = clientAddress || "(no client-facing address configured -- see warning above)"}
          {@const portSuffix = settings.doh3_port === 443 ? "" : `:${settings.doh3_port}`}
          <div class="manual-setup">
            <p class="manual-setup-label">Manual setup (a client that specifically supports HTTP/3 DoH):</p>
            <code>https://{addr}{portSuffix}{settings.doh_path}</code>
            {#if clientAddress && !clientAddressCertValid}
              <p class="hint blocked">This won't validate yet -- the certificate doesn't cover "{addr}" (see warning above).</p>
            {/if}
            <p class="hint">
              Same URL shape as the DoH transport above -- HTTP/3 is a negotiated transport, not a
              separate URL scheme: a client that supports it upgrades to QUIC/HTTP-3 automatically
              against this same HTTPS URL, while most DoH clients (browsers included) will simply
              keep using HTTP/2 against it. If a client doesn't explicitly document DoH3/HTTP-3
              support, use the DoH transport instead -- the effective result is identical either way.
            </p>
          </div>
        {/if}
      </fieldset>

      <fieldset>
        <legend>
          <label><input type="checkbox" bind:checked={settings.dnscrypt_enabled} disabled={!settings.dnscrypt_identity_provisioned} /> DNSCrypt</label>
        </legend>
        <p class="transport-desc">
          An older encrypted DNS protocol with its own resolver-identity format (a provider name +
          public-key fingerprint, not a TLS certificate) -- supported by DNSCrypt-specific clients
          such as dnscrypt-proxy.
        </p>
        <label class="port">Port <input type="number" min="1" max="65535" bind:value={settings.dnscrypt_port} /></label>
        <label class="path">Provider name <input bind:value={settings.dnscrypt_provider_name} /></label>
        {#if !settings.dnscrypt_identity_provisioned}
          <p class="hint">No provider identity yet -- generate one before DNSCrypt can be enabled.</p>
          <button type="button" onclick={() => rotateDnscrypt(false)} disabled={rotateBusy}>
            {rotateBusy ? "Generating…" : "Generate identity"}
          </button>
        {:else}
          {#if settings.dnscrypt_enabled}
            {@const addr = clientAddress || "(no client-facing address configured -- see warning above)"}
            <div class="manual-setup">
              <p class="manual-setup-label">Stamp (paste directly into any DNSCrypt client that accepts one):</p>
              {#if settings.dnscrypt_stamp}
                <code>{settings.dnscrypt_stamp}</code>
              {:else}
                <p class="hint blocked">No stamp yet: no client-facing address is configured (see warning above).</p>
              {/if}
              <p class="manual-setup-label">Static resolver config (e.g. dnscrypt-proxy):</p>
              <code>server_address = '{addr}:{settings.dnscrypt_port}'</code>
              <code>provider_name = '{settings.dnscrypt_provider_name}'</code>
              <code>provider_key = '{settings.dnscrypt_fingerprint}'</code>
              <p class="hint">
                DNSCrypt doesn't use this appliance's TLS certificate at all -- the provider key
                above (pinned in the stamp) is its own trust anchor, so this setup isn't affected by
                the certificate warning at the top of this page.
              </p>
            </div>
          {/if}
          <dl class="cert-info">
            <dt>Fingerprint</dt>
            <dd class="fingerprint">{settings.dnscrypt_fingerprint}</dd>
            <dt>Certificate serial</dt>
            <dd>{settings.dnscrypt_cert_serial}</dd>
            <dt>Certificate valid</dt>
            <dd>
              {settings.dnscrypt_cert_valid_from ? timestampPref.format(new Date(settings.dnscrypt_cert_valid_from * 1000).toISOString()) : "?"} &ndash;
              {settings.dnscrypt_cert_valid_until ? timestampPref.format(new Date(settings.dnscrypt_cert_valid_until * 1000).toISOString()) : "?"}
            </dd>
          </dl>
          <div class="actions">
            <button type="button" onclick={() => rotateDnscrypt(false)} disabled={rotateBusy}>
              {rotateBusy ? "Working…" : "Renew certificate"}
            </button>
            <button type="button" class="danger" onclick={() => rotateDnscrypt(true)} disabled={rotateBusy}>
              {rotateBusy ? "Working…" : "Rotate provider identity"}
            </button>
          </div>
          <p class="hint">
            Rotating the provider identity invalidates every client's existing pinned stamp -- only
            do this if the current identity may be compromised, not for routine certificate renewal.
          </p>
        {/if}
        {#if rotateResult}<p class="success" role="status">{rotateResult}</p>{/if}
        {#if rotateError}<p class="error" role="alert">{rotateError}</p>{/if}
      </fieldset>

      <div class="actions">
        <button type="submit" disabled={saving}>{saving ? "Saving…" : "Save"}</button>
      </div>
      {#if saveResult}<p class="success" role="status">{saveResult}</p>{/if}
      {#if saveError}<p class="error" role="alert">{saveError}</p>{/if}
      <DnsRuntimeBadge result={dnsRuntimeResult} />
    </form>
  {/if}
</section>

{#if confirmRotateProvider}
  <ConfirmDialog
    title="Rotate provider identity"
    message="Rotating the provider identity invalidates every client's existing pinned DNSCrypt stamp. Continue?"
    confirmLabel="Rotate"
    onConfirm={() => {
      confirmRotateProvider = false;
      doRotateDnscrypt(true);
    }}
    onCancel={() => (confirmRotateProvider = false)}
  />
{/if}

<style>
  .encryption { display: flex; flex-direction: column; gap: 1rem; }
  .scope-note { font-size: 0.85rem; opacity: 0.75; max-width: 50rem; }
  .card { border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.25rem; background: var(--card-bg); display: flex; flex-direction: column; gap: 0.75rem; }
  .card h3 { margin: 0; }
  .cert-info { display: grid; grid-template-columns: max-content 1fr; gap: 0.3rem 1rem; font-size: 0.9rem; }
  .cert-info dt { opacity: 0.7; }
  .cert-info dd { margin: 0; }
  .replace-form { display: flex; flex-direction: column; gap: 0.5rem; border-top: 1px solid var(--border); padding-top: 0.75rem; margin-top: 0.25rem; }
  .replace-form h4 { margin: 0; font-size: 0.85rem; }
  .replace-form label { display: flex; flex-direction: column; gap: 0.2rem; font-size: 0.85rem; }
  .transports fieldset { border: 1px solid var(--border); border-radius: 6px; padding: 0.6rem 0.9rem; display: flex; flex-wrap: wrap; align-items: center; gap: 0.75rem; }
  .transports legend { padding: 0 0.3rem; font-weight: 600; }
  .transports label { display: flex; align-items: center; gap: 0.4rem; font-size: 0.85rem; }
  .transports input[type="number"] { width: 6rem; }
  .mobileconfig-link { font-size: 0.82rem; color: var(--accent); text-decoration: underline; }
  .transport-desc { font-size: 0.82rem; opacity: 0.75; margin: 0; flex-basis: 100%; }
  .manual-setup { flex-basis: 100%; display: flex; flex-direction: column; gap: 0.2rem; background: var(--attention-bg); border-radius: 6px; padding: 0.5rem 0.75rem; }
  .manual-setup-label { font-size: 0.78rem; opacity: 0.8; margin: 0; }
  .manual-setup code { font-size: 0.82rem; font-family: monospace; user-select: all; }
  .actions { display: flex; align-items: center; gap: 0.6rem; }
  .fingerprint { font-family: monospace; font-size: 0.82rem; word-break: break-all; }
  button.danger { color: var(--badge-danger-fg); border-color: var(--badge-danger-fg); }
  .success { color: var(--success); }
  .error { color: var(--badge-danger-fg); }
  .degraded-note { background: var(--badge-warn-bg); color: var(--badge-warn-fg); padding: 0.5rem 0.75rem; border-radius: 6px; font-size: 0.85rem; }
  .hint { font-size: 0.8rem; opacity: 0.7; }
  .hint.blocked { opacity: 1; color: var(--badge-danger-fg); font-weight: 500; }
  .hint.local-only { opacity: 1; color: var(--badge-warn-fg); }
</style>
