package hostagentd

import (
	"os"
	"path/filepath"
	"testing"
)

// TestAdoptDnsdistAPIKeyFromLiveConfig is the direct regression proof
// for a real, previously-undiscovered defect: dnsdistAPIKey is
// deliberately in-memory-only on this side (dnsRuntimeState's own doc
// comment), correct for its original purpose, but every hostagent
// restart -- which happens on every routine redeploy, not a rare event
// -- wiped it back to empty even though dnsdist itself kept running
// fine with the same key. This recovers it from the config file
// dnsdist is actually running with, the exact real shape
// internal/dnscompile.go emits (confirmed against the real live
// appliance's own compiled dnsdist.conf).
func TestAdoptDnsdistAPIKeyFromLiveConfig(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "dnsdist.conf")
	// Exact real shape, byte-for-byte, from the live appliance's own
	// compiled dnsdist.conf (see internal/dnscompile.go's own webserver
	// block).
	content := `-- Generated by internal/dnscompile -- Go-native DNS runtime compiler.
-- Do not hand-edit; regenerate from the effective Go control-plane state.
setLocal("0.0.0.0:53")

webserver("127.0.0.1:8083")
setWebserverConfig({
  acl="127.0.0.1/32,::1/128",
  apiKey="lZIOlfjYoZ3jO6zVsu1J97nHK5agPfvJ"
})
setAPIWritable(false)
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	key, port := adoptDnsdistAPIKeyFromLiveConfig(path)
	if key != "lZIOlfjYoZ3jO6zVsu1J97nHK5agPfvJ" {
		t.Fatalf("expected the real key to be recovered, got %q", key)
	}
	if port != 8083 {
		t.Fatalf("expected the real compiled port to be recovered, got %d", port)
	}
}

func TestAdoptDnsdistAPIKeyFromLiveConfigNoKeyCompiled(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "dnsdist.conf")
	// No webserver()/apiKey= at all -- the real shape when DNSCrypt/no
	// transports needing the API were ever enabled.
	content := `setLocal("0.0.0.0:53")
newServer({address="127.0.0.1:26553", pool="", useProxyProtocol=true, name="apdns_bind_backend"})
`
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	key, port := adoptDnsdistAPIKeyFromLiveConfig(path)
	if key != "" || port != 0 {
		t.Fatalf("expected an honest empty result when no API key was ever compiled, got key=%q port=%d", key, port)
	}
}

func TestAdoptDnsdistAPIKeyFromLiveConfigMissingFile(t *testing.T) {
	key, port := adoptDnsdistAPIKeyFromLiveConfig(filepath.Join(t.TempDir(), "does-not-exist.conf"))
	if key != "" || port != 0 {
		t.Fatalf("expected an honest empty result for a missing file, got key=%q port=%d", key, port)
	}
}
